/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CheapFlightsRouteImport } from './routes/cheap-flights'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as LiveRoomCodeRouteImport } from './routes/live-room.$code'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiTtsRouteImport } from './routes/api.tts'
import { Route as ApiJaxRouteImport } from './routes/api.jax'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiAiRouteImport } from './routes/api.ai'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as AppTranslatorRouteImport } from './routes/_app.translator'
import { Route as AppStaysRouteImport } from './routes/_app.stays'
import { Route as AppShieldRouteImport } from './routes/_app.shield'
import { Route as AppReferralsRouteImport } from './routes/_app.referrals'
import { Route as AppPlannerRouteImport } from './routes/_app.planner'
import { Route as AppLiveTranslatorRouteImport } from './routes/_app.live-translator'
import { Route as AppFlightsRouteImport } from './routes/_app.flights'
import { Route as AppFileTranslatorRouteImport } from './routes/_app.file-translator'
import { Route as AppDealsRouteImport } from './routes/_app.deals'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCreditsRouteImport } from './routes/_app.credits'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as ApiPublicWidgetItineraryRouteImport } from './routes/api.public.widget-itinerary'
import { Route as ApiPublicTtsRouteImport } from './routes/api.public.tts'
import { Route as ApiPublicTranslateBroadcastRouteImport } from './routes/api.public.translate-broadcast'
import { Route as ApiPublicSttRouteImport } from './routes/api.public.stt'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app.settings.appearance'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppAdminMystiflyTestRouteImport } from './routes/_app.admin.mystifly-test'
import { Route as AppAdminMystiflyRouteImport } from './routes/_app.admin.mystifly'
import { Route as AppAdminFinancialRouteImport } from './routes/_app.admin.financial'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api.public.payments.webhook'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api.public.mercadopago.webhook'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheapFlightsRoute = CheapFlightsRouteImport.update({
  id: '/cheap-flights',
  path: '/cheap-flights',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoomCodeRoute = LiveRoomCodeRouteImport.update({
  id: '/live-room/$code',
  path: '/live-room/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJaxRoute = ApiJaxRouteImport.update({
  id: '/api/jax',
  path: '/api/jax',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTranslatorRoute = AppTranslatorRouteImport.update({
  id: '/translator',
  path: '/translator',
  getParentRoute: () => AppRoute,
} as any)
const AppStaysRoute = AppStaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => AppRoute,
} as any)
const AppShieldRoute = AppShieldRouteImport.update({
  id: '/shield',
  path: '/shield',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralsRoute = AppReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveTranslatorRoute = AppLiveTranslatorRouteImport.update({
  id: '/live-translator',
  path: '/live-translator',
  getParentRoute: () => AppRoute,
} as any)
const AppFlightsRoute = AppFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => AppRoute,
} as any)
const AppFileTranslatorRoute = AppFileTranslatorRouteImport.update({
  id: '/file-translator',
  path: '/file-translator',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsRoute = AppDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditsRoute = AppCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWidgetItineraryRoute =
  ApiPublicWidgetItineraryRouteImport.update({
    id: '/api/public/widget-itinerary',
    path: '/api/public/widget-itinerary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTtsRoute = ApiPublicTtsRouteImport.update({
  id: '/api/public/tts',
  path: '/api/public/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranslateBroadcastRoute =
  ApiPublicTranslateBroadcastRouteImport.update({
    id: '/api/public/translate-broadcast',
    path: '/api/public/translate-broadcast',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSttRoute = ApiPublicSttRouteImport.update({
  id: '/api/public/stt',
  path: '/api/public/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/settings/appearance',
  path: '/settings/appearance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMystiflyTestRoute = AppAdminMystiflyTestRouteImport.update({
  id: '/admin/mystifly-test',
  path: '/admin/mystifly-test',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMystiflyRoute = AppAdminMystiflyRouteImport.update({
  id: '/admin/mystifly',
  path: '/admin/mystifly',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminFinancialRoute = AppAdminFinancialRouteImport.update({
  id: '/admin/financial',
  path: '/admin/financial',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago/webhook',
    path: '/api/public/mercadopago/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cheap-flights': typeof CheapFlightsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/billing': typeof AppBillingRoute
  '/chat': typeof AppChatRoute
  '/credits': typeof AppCreditsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deals': typeof AppDealsRoute
  '/file-translator': typeof AppFileTranslatorRoute
  '/flights': typeof AppFlightsRoute
  '/live-translator': typeof AppLiveTranslatorRoute
  '/planner': typeof AppPlannerRoute
  '/referrals': typeof AppReferralsRoute
  '/shield': typeof AppShieldRoute
  '/stays': typeof AppStaysRoute
  '/translator': typeof AppTranslatorRoute
  '/wallet': typeof AppWalletRoute
  '/api/ai': typeof ApiAiRoute
  '/api/chat': typeof ApiChatRoute
  '/api/jax': typeof ApiJaxRoute
  '/api/tts': typeof ApiTtsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/live-room/$code': typeof LiveRoomCodeRoute
  '/r/$slug': typeof RSlugRoute
  '/admin/financial': typeof AppAdminFinancialRoute
  '/admin/mystifly': typeof AppAdminMystiflyRoute
  '/admin/mystifly-test': typeof AppAdminMystiflyTestRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/api/public/stt': typeof ApiPublicSttRoute
  '/api/public/translate-broadcast': typeof ApiPublicTranslateBroadcastRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/widget-itinerary': typeof ApiPublicWidgetItineraryRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cheap-flights': typeof CheapFlightsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/billing': typeof AppBillingRoute
  '/chat': typeof AppChatRoute
  '/credits': typeof AppCreditsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deals': typeof AppDealsRoute
  '/file-translator': typeof AppFileTranslatorRoute
  '/flights': typeof AppFlightsRoute
  '/live-translator': typeof AppLiveTranslatorRoute
  '/planner': typeof AppPlannerRoute
  '/referrals': typeof AppReferralsRoute
  '/shield': typeof AppShieldRoute
  '/stays': typeof AppStaysRoute
  '/translator': typeof AppTranslatorRoute
  '/wallet': typeof AppWalletRoute
  '/api/ai': typeof ApiAiRoute
  '/api/chat': typeof ApiChatRoute
  '/api/jax': typeof ApiJaxRoute
  '/api/tts': typeof ApiTtsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/live-room/$code': typeof LiveRoomCodeRoute
  '/r/$slug': typeof RSlugRoute
  '/admin/financial': typeof AppAdminFinancialRoute
  '/admin/mystifly': typeof AppAdminMystiflyRoute
  '/admin/mystifly-test': typeof AppAdminMystiflyTestRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/api/public/stt': typeof ApiPublicSttRoute
  '/api/public/translate-broadcast': typeof ApiPublicTranslateBroadcastRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/widget-itinerary': typeof ApiPublicWidgetItineraryRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/cheap-flights': typeof CheapFlightsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/credits': typeof AppCreditsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deals': typeof AppDealsRoute
  '/_app/file-translator': typeof AppFileTranslatorRoute
  '/_app/flights': typeof AppFlightsRoute
  '/_app/live-translator': typeof AppLiveTranslatorRoute
  '/_app/planner': typeof AppPlannerRoute
  '/_app/referrals': typeof AppReferralsRoute
  '/_app/shield': typeof AppShieldRoute
  '/_app/stays': typeof AppStaysRoute
  '/_app/translator': typeof AppTranslatorRoute
  '/_app/wallet': typeof AppWalletRoute
  '/api/ai': typeof ApiAiRoute
  '/api/chat': typeof ApiChatRoute
  '/api/jax': typeof ApiJaxRoute
  '/api/tts': typeof ApiTtsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/live-room/$code': typeof LiveRoomCodeRoute
  '/r/$slug': typeof RSlugRoute
  '/_app/admin/financial': typeof AppAdminFinancialRoute
  '/_app/admin/mystifly': typeof AppAdminMystiflyRoute
  '/_app/admin/mystifly-test': typeof AppAdminMystiflyTestRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/api/public/stt': typeof ApiPublicSttRoute
  '/api/public/translate-broadcast': typeof ApiPublicTranslateBroadcastRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/widget-itinerary': typeof ApiPublicWidgetItineraryRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cheap-flights'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/billing'
    | '/chat'
    | '/credits'
    | '/dashboard'
    | '/deals'
    | '/file-translator'
    | '/flights'
    | '/live-translator'
    | '/planner'
    | '/referrals'
    | '/shield'
    | '/stays'
    | '/translator'
    | '/wallet'
    | '/api/ai'
    | '/api/chat'
    | '/api/jax'
    | '/api/tts'
    | '/auth/callback'
    | '/checkout/return'
    | '/live-room/$code'
    | '/r/$slug'
    | '/admin/financial'
    | '/admin/mystifly'
    | '/admin/mystifly-test'
    | '/admin/settings'
    | '/settings/appearance'
    | '/api/public/stt'
    | '/api/public/translate-broadcast'
    | '/api/public/tts'
    | '/api/public/widget-itinerary'
    | '/api/public/mercadopago/webhook'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cheap-flights'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/billing'
    | '/chat'
    | '/credits'
    | '/dashboard'
    | '/deals'
    | '/file-translator'
    | '/flights'
    | '/live-translator'
    | '/planner'
    | '/referrals'
    | '/shield'
    | '/stays'
    | '/translator'
    | '/wallet'
    | '/api/ai'
    | '/api/chat'
    | '/api/jax'
    | '/api/tts'
    | '/auth/callback'
    | '/checkout/return'
    | '/live-room/$code'
    | '/r/$slug'
    | '/admin/financial'
    | '/admin/mystifly'
    | '/admin/mystifly-test'
    | '/admin/settings'
    | '/settings/appearance'
    | '/api/public/stt'
    | '/api/public/translate-broadcast'
    | '/api/public/tts'
    | '/api/public/widget-itinerary'
    | '/api/public/mercadopago/webhook'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/cheap-flights'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/billing'
    | '/_app/chat'
    | '/_app/credits'
    | '/_app/dashboard'
    | '/_app/deals'
    | '/_app/file-translator'
    | '/_app/flights'
    | '/_app/live-translator'
    | '/_app/planner'
    | '/_app/referrals'
    | '/_app/shield'
    | '/_app/stays'
    | '/_app/translator'
    | '/_app/wallet'
    | '/api/ai'
    | '/api/chat'
    | '/api/jax'
    | '/api/tts'
    | '/auth/callback'
    | '/checkout/return'
    | '/live-room/$code'
    | '/r/$slug'
    | '/_app/admin/financial'
    | '/_app/admin/mystifly'
    | '/_app/admin/mystifly-test'
    | '/_app/admin/settings'
    | '/_app/settings/appearance'
    | '/api/public/stt'
    | '/api/public/translate-broadcast'
    | '/api/public/tts'
    | '/api/public/widget-itinerary'
    | '/api/public/mercadopago/webhook'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CheapFlightsRoute: typeof CheapFlightsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiJaxRoute: typeof ApiJaxRoute
  ApiTtsRoute: typeof ApiTtsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  LiveRoomCodeRoute: typeof LiveRoomCodeRoute
  RSlugRoute: typeof RSlugRoute
  ApiPublicSttRoute: typeof ApiPublicSttRoute
  ApiPublicTranslateBroadcastRoute: typeof ApiPublicTranslateBroadcastRoute
  ApiPublicTtsRoute: typeof ApiPublicTtsRoute
  ApiPublicWidgetItineraryRoute: typeof ApiPublicWidgetItineraryRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheap-flights': {
      id: '/cheap-flights'
      path: '/cheap-flights'
      fullPath: '/cheap-flights'
      preLoaderRoute: typeof CheapFlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-room/$code': {
      id: '/live-room/$code'
      path: '/live-room/$code'
      fullPath: '/live-room/$code'
      preLoaderRoute: typeof LiveRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jax': {
      id: '/api/jax'
      path: '/api/jax'
      fullPath: '/api/jax'
      preLoaderRoute: typeof ApiJaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/translator': {
      id: '/_app/translator'
      path: '/translator'
      fullPath: '/translator'
      preLoaderRoute: typeof AppTranslatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stays': {
      id: '/_app/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof AppStaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shield': {
      id: '/_app/shield'
      path: '/shield'
      fullPath: '/shield'
      preLoaderRoute: typeof AppShieldRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/referrals': {
      id: '/_app/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AppReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live-translator': {
      id: '/_app/live-translator'
      path: '/live-translator'
      fullPath: '/live-translator'
      preLoaderRoute: typeof AppLiveTranslatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flights': {
      id: '/_app/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof AppFlightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/file-translator': {
      id: '/_app/file-translator'
      path: '/file-translator'
      fullPath: '/file-translator'
      preLoaderRoute: typeof AppFileTranslatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals': {
      id: '/_app/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AppDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credits': {
      id: '/_app/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AppCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/widget-itinerary': {
      id: '/api/public/widget-itinerary'
      path: '/api/public/widget-itinerary'
      fullPath: '/api/public/widget-itinerary'
      preLoaderRoute: typeof ApiPublicWidgetItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts': {
      id: '/api/public/tts'
      path: '/api/public/tts'
      fullPath: '/api/public/tts'
      preLoaderRoute: typeof ApiPublicTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/translate-broadcast': {
      id: '/api/public/translate-broadcast'
      path: '/api/public/translate-broadcast'
      fullPath: '/api/public/translate-broadcast'
      preLoaderRoute: typeof ApiPublicTranslateBroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stt': {
      id: '/api/public/stt'
      path: '/api/public/stt'
      fullPath: '/api/public/stt'
      preLoaderRoute: typeof ApiPublicSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/mystifly-test': {
      id: '/_app/admin/mystifly-test'
      path: '/admin/mystifly-test'
      fullPath: '/admin/mystifly-test'
      preLoaderRoute: typeof AppAdminMystiflyTestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/mystifly': {
      id: '/_app/admin/mystifly'
      path: '/admin/mystifly'
      fullPath: '/admin/mystifly'
      preLoaderRoute: typeof AppAdminMystiflyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/financial': {
      id: '/_app/admin/financial'
      path: '/admin/financial'
      fullPath: '/admin/financial'
      preLoaderRoute: typeof AppAdminFinancialRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago/webhook': {
      id: '/api/public/mercadopago/webhook'
      path: '/api/public/mercadopago/webhook'
      fullPath: '/api/public/mercadopago/webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppChatRoute: typeof AppChatRoute
  AppCreditsRoute: typeof AppCreditsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDealsRoute: typeof AppDealsRoute
  AppFileTranslatorRoute: typeof AppFileTranslatorRoute
  AppFlightsRoute: typeof AppFlightsRoute
  AppLiveTranslatorRoute: typeof AppLiveTranslatorRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppReferralsRoute: typeof AppReferralsRoute
  AppShieldRoute: typeof AppShieldRoute
  AppStaysRoute: typeof AppStaysRoute
  AppTranslatorRoute: typeof AppTranslatorRoute
  AppWalletRoute: typeof AppWalletRoute
  AppAdminFinancialRoute: typeof AppAdminFinancialRoute
  AppAdminMystiflyRoute: typeof AppAdminMystiflyRoute
  AppAdminMystiflyTestRoute: typeof AppAdminMystiflyTestRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppChatRoute: AppChatRoute,
  AppCreditsRoute: AppCreditsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDealsRoute: AppDealsRoute,
  AppFileTranslatorRoute: AppFileTranslatorRoute,
  AppFlightsRoute: AppFlightsRoute,
  AppLiveTranslatorRoute: AppLiveTranslatorRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppReferralsRoute: AppReferralsRoute,
  AppShieldRoute: AppShieldRoute,
  AppStaysRoute: AppStaysRoute,
  AppTranslatorRoute: AppTranslatorRoute,
  AppWalletRoute: AppWalletRoute,
  AppAdminFinancialRoute: AppAdminFinancialRoute,
  AppAdminMystiflyRoute: AppAdminMystiflyRoute,
  AppAdminMystiflyTestRoute: AppAdminMystiflyTestRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CheapFlightsRoute: CheapFlightsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiAiRoute: ApiAiRoute,
  ApiChatRoute: ApiChatRoute,
  ApiJaxRoute: ApiJaxRoute,
  ApiTtsRoute: ApiTtsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  LiveRoomCodeRoute: LiveRoomCodeRoute,
  RSlugRoute: RSlugRoute,
  ApiPublicSttRoute: ApiPublicSttRoute,
  ApiPublicTranslateBroadcastRoute: ApiPublicTranslateBroadcastRoute,
  ApiPublicTtsRoute: ApiPublicTtsRoute,
  ApiPublicWidgetItineraryRoute: ApiPublicWidgetItineraryRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
